name: Sync to Hugging Face

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install rsync
        run: |
          sudo apt-get update
          sudo apt-get install -y rsync

      - name: Push To Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"

          # استخدام x مكان اسم المستخدم بيحل مشاكل الحروف وحالة الأحرف مع Git
          git clone https://x:$HF_TOKEN@huggingface.co/spaces/7atemmmmm/titanx-beta hf_space

          rsync -av --delete \
            --exclude ".git" \
            --exclude ".github" \
            ./ hf_space/

          cd hf_space
          git add .

          if ! git diff --cached --quiet; then
            git commit -m "Auto sync from GitHub"
            # استخدام force-- عشان لو الـ Space فيها ملفات تلقائية زي README ما يحصلش تعارض ويبوظ الرفع
            git push origin main --force
          fi
